{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e36df9c8-582f-4441-b933-e80f7bfba48c",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "answer:\n",
    "When creating a custom exception in a programming language like Python, it's typically recommended to subclass the built-in Exception class. Here's why:\n",
    "\n",
    "Consistency and Standardization: In most programming languages, including Python, the Exception class serves as the base class for all exceptions.\n",
    "By subclassing Exception, you're adhering to the standard convention followed by the language, which makes your code more understandable \n",
    "and predictable for other developers.\n",
    "\n",
    "Inheritance and Hierarchy: Subclassing Exception allows your custom exception to inherit all the behaviors and attributes of the base Exception class.\n",
    "This includes features like stack traces, error messages, and other methods relevant to exception handling.\n",
    "It also maintains a clear hierarchy of exceptions, making it easier to organize and manage different types of errors in your codebase\n",
    "\n",
    "Interoperability: Using the Exception class ensures that your custom exception seamlessly integrates with existing exception handling mechanisms\n",
    "in the language.It allows your custom exception to be caught and handled alongside built-in exceptions using try-except blocks\n",
    "without any additional modifications.\n",
    "\n",
    "Documentation and Understanding: Subclassing Exception provides clear documentation and signaling to other developers that your class is intended\n",
    "to be used as an exception. It improves code readability and helps in understanding the purpose of your custom exception without needing\n",
    "additional comments or explanations.\n",
    "\n",
    "Future Compatibility: Base classes like Exception are unlikely to undergo significant changes in future language updates.\n",
    "By relying on such fundamental classes, you ensure that your custom exceptions remain compatible with future versions of the language"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "30f1610b-b3f7-4aac-b15d-9e3ba33f7c11",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "answer:\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "58533ce3-b5a5-4e08-ad5b-2a42c4989a6a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Python Exception Hierarchy:\n",
      "BaseException\n",
      "BaseExceptionGroup\n",
      "ExceptionGroup\n",
      "Exception\n",
      "ArithmeticError\n",
      "FloatingPointError\n",
      "OverflowError\n",
      "ZeroDivisionError\n",
      "DivisionByZero\n",
      "DivisionUndefined\n",
      "DecimalException\n",
      "Clamped\n",
      "Rounded\n",
      "Underflow\n",
      "Overflow\n",
      "Inexact\n",
      "Underflow\n",
      "Overflow\n",
      "Subnormal\n",
      "Underflow\n",
      "DivisionByZero\n",
      "FloatOperation\n",
      "InvalidOperation\n",
      "ConversionSyntax\n",
      "DivisionImpossible\n",
      "DivisionUndefined\n",
      "InvalidContext\n",
      "AssertionError\n",
      "AttributeError\n",
      "FrozenInstanceError\n",
      "BufferError\n",
      "EOFError\n",
      "IncompleteReadError\n",
      "ImportError\n",
      "ModuleNotFoundError\n",
      "PackageNotFoundError\n",
      "ZipImportError\n",
      "LookupError\n",
      "IndexError\n",
      "KeyError\n",
      "NoSuchKernel\n",
      "UnknownBackend\n",
      "CodecRegistryError\n",
      "MemoryError\n",
      "NameError\n",
      "UnboundLocalError\n",
      "OSError\n",
      "BlockingIOError\n",
      "ChildProcessError\n",
      "ConnectionError\n",
      "BrokenPipeError\n",
      "ConnectionAbortedError\n",
      "ConnectionRefusedError\n",
      "ConnectionResetError\n",
      "RemoteDisconnected\n",
      "FileExistsError\n",
      "FileNotFoundError\n",
      "InterruptedError\n",
      "InterruptedSystemCall\n",
      "IsADirectoryError\n",
      "NotADirectoryError\n",
      "PermissionError\n",
      "ProcessLookupError\n",
      "TimeoutError\n",
      "UnsupportedOperation\n",
      "herror\n",
      "gaierror\n",
      "SSLError\n",
      "SSLCertVerificationError\n",
      "SSLZeroReturnError\n",
      "SSLWantWriteError\n",
      "SSLWantReadError\n",
      "SSLSyscallError\n",
      "SSLEOFError\n",
      "Error\n",
      "SameFileError\n",
      "SpecialFileError\n",
      "ExecError\n",
      "ReadError\n",
      "URLError\n",
      "HTTPError\n",
      "ContentTooShortError\n",
      "BadGzipFile\n",
      "ReferenceError\n",
      "RuntimeError\n",
      "NotImplementedError\n",
      "ZMQVersionError\n",
      "StdinNotImplementedError\n",
      "RecursionError\n",
      "_DeadlockError\n",
      "BrokenBarrierError\n",
      "BrokenExecutor\n",
      "BrokenThreadPool\n",
      "SendfileNotAvailableError\n",
      "BrokenBarrierError\n",
      "VariableError\n",
      "StopAsyncIteration\n",
      "StopIteration\n",
      "SyntaxError\n",
      "IndentationError\n",
      "TabError\n",
      "SystemError\n",
      "CodecRegistryError\n",
      "TypeError\n",
      "FloatOperation\n",
      "MultipartConversionError\n",
      "ValueError\n",
      "UnicodeError\n",
      "UnicodeDecodeError\n",
      "UnicodeEncodeError\n",
      "UnicodeTranslateError\n",
      "UnsupportedOperation\n",
      "JSONDecodeError\n",
      "UnsupportedDigestmodError\n",
      "SSLCertVerificationError\n",
      "Error\n",
      "AddressValueError\n",
      "NetmaskValueError\n",
      "IllegalMonthError\n",
      "IllegalWeekdayError\n",
      "ParserError\n",
      "MessageDefect\n",
      "NoBoundaryInMultipartDefect\n",
      "StartBoundaryNotFoundDefect\n",
      "CloseBoundaryNotFoundDefect\n",
      "FirstHeaderLineIsContinuationDefect\n",
      "MisplacedEnvelopeHeaderDefect\n",
      "MissingHeaderBodySeparatorDefect\n",
      "MultipartInvariantViolationDefect\n",
      "InvalidMultipartContentTransferEncodingDefect\n",
      "UndecodableBytesDefect\n",
      "InvalidBase64PaddingDefect\n",
      "InvalidBase64CharactersDefect\n",
      "InvalidBase64LengthDefect\n",
      "HeaderDefect\n",
      "InvalidHeaderDefect\n",
      "HeaderMissingRequiredValue\n",
      "NonPrintableDefect\n",
      "ObsoleteHeaderDefect\n",
      "NonASCIILocalPartDefect\n",
      "InvalidDateDefect\n",
      "ClassNotFound\n",
      "ClipboardEmpty\n",
      "MacroToEdit\n",
      "InvalidVersion\n",
      "Warning\n",
      "BytesWarning\n",
      "DeprecationWarning\n",
      "ProvisionalWarning\n",
      "EncodingWarning\n",
      "FutureWarning\n",
      "ProvisionalCompleterWarning\n",
      "ImportWarning\n",
      "PendingDeprecationWarning\n",
      "ResourceWarning\n",
      "RuntimeWarning\n",
      "ProactorSelectorThreadWarning\n",
      "UnknownTimezoneWarning\n",
      "SyntaxWarning\n",
      "UnicodeWarning\n",
      "UserWarning\n",
      "GetPassWarning\n",
      "FormatterWarning\n",
      "DeprecatedTzFormatWarning\n",
      "ExceptionGroup\n",
      "_OptionError\n",
      "_Error\n",
      "error\n",
      "Error\n",
      "SubprocessError\n",
      "CalledProcessError\n",
      "TimeoutExpired\n",
      "ZMQBaseError\n",
      "ZMQError\n",
      "ContextTerminated\n",
      "Again\n",
      "InterruptedSystemCall\n",
      "ZMQBindError\n",
      "NotDone\n",
      "Error\n",
      "error\n",
      "PickleError\n",
      "PicklingError\n",
      "UnpicklingError\n",
      "_Stop\n",
      "TokenError\n",
      "StopTokenizing\n",
      "Error\n",
      "CancelledError\n",
      "InvalidStateError\n",
      "_GiveupOnSendfile\n",
      "Incomplete\n",
      "ClassFoundException\n",
      "EndOfBlock\n",
      "InvalidStateError\n",
      "LimitOverrunError\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "error\n",
      "LZMAError\n",
      "RegistryError\n",
      "_GiveupOnFastCopy\n",
      "TraitError\n",
      "Empty\n",
      "Full\n",
      "ArgumentError\n",
      "COMError\n",
      "ReturnValueIgnoredError\n",
      "ArgumentError\n",
      "ArgumentTypeError\n",
      "ConfigError\n",
      "ConfigLoaderError\n",
      "ArgumentError\n",
      "ConfigFileNotFound\n",
      "ConfigurableError\n",
      "MultipleInstanceError\n",
      "ApplicationError\n",
      "InvalidPortNumber\n",
      "NoIPAddresses\n",
      "Error\n",
      "BadZipFile\n",
      "LargeZipFile\n",
      "MessageError\n",
      "MessageParseError\n",
      "HeaderParseError\n",
      "BoundaryError\n",
      "MultipartConversionError\n",
      "CharsetError\n",
      "TraversalError\n",
      "DuplicateKernelError\n",
      "ErrorDuringImport\n",
      "NotOneValueFound\n",
      "KnownIssue\n",
      "VerifierFailure\n",
      "CannotEval\n",
      "OptionError\n",
      "BdbQuit\n",
      "Restart\n",
      "FindCmdError\n",
      "HomeDirError\n",
      "ProfileDirError\n",
      "IPythonCoreError\n",
      "TryNext\n",
      "UsageError\n",
      "StdinNotImplementedError\n",
      "InputRejected\n",
      "GetoptError\n",
      "ErrorToken\n",
      "PrefilterError\n",
      "AliasError\n",
      "InvalidAliasError\n",
      "Error\n",
      "InterfaceError\n",
      "DatabaseError\n",
      "InternalError\n",
      "OperationalError\n",
      "ProgrammingError\n",
      "IntegrityError\n",
      "DataError\n",
      "NotSupportedError\n",
      "Warning\n",
      "SpaceInInput\n",
      "DOMException\n",
      "IndexSizeErr\n",
      "DomstringSizeErr\n",
      "HierarchyRequestErr\n",
      "WrongDocumentErr\n",
      "InvalidCharacterErr\n",
      "NoDataAllowedErr\n",
      "NoModificationAllowedErr\n",
      "NotFoundErr\n",
      "NotSupportedErr\n",
      "InuseAttributeErr\n",
      "InvalidStateErr\n",
      "SyntaxErr\n",
      "InvalidModificationErr\n",
      "NamespaceErr\n",
      "InvalidAccessErr\n",
      "ValidationErr\n",
      "ValidationError\n",
      "EditReadOnlyBuffer\n",
      "_Retry\n",
      "InvalidLayoutError\n",
      "HeightIsUnknownError\n",
      "GuardRejection\n",
      "ParserSyntaxError\n",
      "InternalParseError\n",
      "_PositionUpdatingFinished\n",
      "SimpleGetItemNotFound\n",
      "UncaughtAttributeError\n",
      "HasNoContext\n",
      "ParamIssue\n",
      "_JediError\n",
      "InternalError\n",
      "WrongVersion\n",
      "RefactoringError\n",
      "OnErrorLeaf\n",
      "InvalidPythonEnvironment\n",
      "HTTPException\n",
      "NotConnected\n",
      "InvalidURL\n",
      "UnknownProtocol\n",
      "UnknownTransferEncoding\n",
      "UnimplementedFileMode\n",
      "IncompleteRead\n",
      "ImproperConnectionState\n",
      "CannotSendRequest\n",
      "CannotSendHeader\n",
      "ResponseNotReady\n",
      "BadStatusLine\n",
      "RemoteDisconnected\n",
      "LineTooLong\n",
      "InteractivelyDefined\n",
      "KillEmbedded\n",
      "Error\n",
      "NoSuchProcess\n",
      "ZombieProcess\n",
      "AccessDenied\n",
      "TimeoutExpired\n",
      "Error\n",
      "TimeoutExpired\n",
      "TimeoutAbandoned\n",
      "KeyReuseError\n",
      "UnknownKeyError\n",
      "LeakedCallbackError\n",
      "BadYieldError\n",
      "ReturnValueIgnoredError\n",
      "Return\n",
      "QueueEmpty\n",
      "QueueFull\n",
      "DebuggerInitializationError\n",
      "ExpatError\n",
      "Error\n",
      "ProtocolError\n",
      "ResponseError\n",
      "Fault\n",
      "_Error\n",
      "UnableToResolveVariableException\n",
      "InvalidTypeInArgsException\n",
      "GeneratorExit\n",
      "KeyboardInterrupt\n",
      "SystemExit\n",
      "CancelledError\n"
     ]
    }
   ],
   "source": [
    "import builtins\n",
    "\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent)\n",
    "\n",
    "print(\"Python Exception Hierarchy:\")\n",
    "print_exception_hierarchy(builtins.BaseException)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2da4401-37d7-43b5-9ef5-0582db8c8fad",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q3.What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "answer:\n",
    "The ArithmeticError class in Python is a base class for exceptions that occur during arithmetic operations. \n",
    "It serves as a parent class for various specific arithmetic-related exception classes. Two commonly encountered errors defined\n",
    "within the ArithmeticError class are:\n",
    "\n",
    "ZeroDivisionError: Raised when a division or modulo operation is attempted with a divisor of zero.\n",
    "\n",
    "OverflowError: Raised when the result of an arithmetic operation is too large to be represented within the available memory or numeric range.\n",
    "Let's explain each with an example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "81759327-aa32-45cc-b8c1-109d851b92da",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    result = 10 / 0  # Attempting to divide by zero\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3b3ea3a-5a0d-46c5-97c9-069e69de3289",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    result = 2 ** 10000\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "af6d6715-0590-4e5a-9835-b5d25faa777e",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "answer:\n",
    "The LookupError class in Python serves as the base class for exceptions that occur when a key or index is not found during a lookup operation.\n",
    "It's a subclass of the Exception class and provides a common base for more specific lookup-related errors.\n",
    "\n",
    "Two common subclasses of LookupError are KeyError and IndexError, which are used when a specified key or index cannot be found in a\n",
    "dictionary or sequence respectively.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "986817c1-d090-4168-8d48-4571fac86785",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "KeyError: 'd'\n"
     ]
    }
   ],
   "source": [
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']  # Trying to access a key that doesn't exist\n",
    "except KeyError as e:\n",
    "    print(\"KeyError:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "d76f3474-9129-4a72-9d92-c8aa62b338fc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "IndexError: list index out of range\n"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3, 4, 5]\n",
    "\n",
    "try:\n",
    "    value = my_list[10]  # Trying to access an index that is out of range\n",
    "except IndexError as e:\n",
    "    print(\"IndexError:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "0c242b1b-ec63-42e6-b90d-9efc160e089a",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (177868793.py, line 3)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[11], line 3\u001b[1;36m\u001b[0m\n\u001b[1;33m    answer:\u001b[0m\n\u001b[1;37m           ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "answer:\n",
    "ImportError is a Python exception that occurs when an import statement fails to import a module. \n",
    "It is a subclass of the Exception class and is raised when there is an issue with importing a module or a sub-module.\n",
    "This error can occur for various reasons, such as the module not existing, being inaccessible, or having syntax errors.\n",
    "ModuleNotFoundError is a subclass of ImportError that specifically indicates \n",
    "that a module could not be found. It was introduced in Python 3.6 to provide more clarity in situations where\n",
    "the interpreter is unable to locate the requested module.\n",
    "                                                                         "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6aebab64-c18e-4207-aebb-4e8d76e178dc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ImportError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module  # Trying to import a module that does not exist\n",
    "except ImportError as e:\n",
    "    print(\"ImportError:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8b918d79-31ab-4e03-bd1f-65389b6aee78",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ModuleNotFoundError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module  # Trying to import a module that does not exist\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"ModuleNotFoundError:\", e)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cd6c49df-4698-47e7-8ebf-2284dce5c64c",
   "metadata": {},
   "outputs": [],
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "answer:\n",
    "Exception handling is an essential aspect of writing robust and maintainable Python code. Here are some best practices for exception handling in Python:\n",
    "                                                                                                                    \n",
    "\n",
    "Handle specific exceptions: Catch specific exceptions rather than using a generic except block. This allows you to handle different types of errors differently and provides more precise error messages for debugging.\n",
    "\n",
    "Use try-except blocks judiciously: Wrap only the code that may raise exceptions in try blocks and handle those exceptions appropriately in except blocks. Avoid wrapping large sections of code if only a small portion may raise an exception.\n",
    "\n",
    "Avoid catching Exception indiscriminately: Catching the base Exception class can mask unexpected errors and make debugging more difficult. Instead, catch specific exceptions relevant to your code's logic.\n",
    "\n",
    "Use finally for cleanup: Use a finally block to ensure that cleanup code (such as closing files or releasing resources) is executed, regardless of whether an exception occurred or not.\n",
    "\n",
    "Handle exceptions gracefully: Provide meaningful error messages and handle exceptions gracefully, whether by logging the error, displaying a user-friendly message, or taking appropriate corrective action.\n",
    "\n",
    "Avoid overly broad try-except blocks: Narrow down the scope of try blocks to only include the code that may raise exceptions. This helps in isolating potential issues and makes the code easier to maintain.\n",
    "\n",
    "Use exception chaining: When catching and handling exceptions, use the raise statement without arguments to re-raise the caught exception. This preserves the original traceback, making debugging easier.\n",
    "\n",
    "Follow the EAFP (Easier to Ask for Forgiveness than Permission) principle: It's often more Pythonic to try an operation and deal with any exceptions that occur, rather than checking beforehand whether the operation will succeed.\n",
    "\n",
    "Document exception handling: Clearly document the exceptions that functions or methods may raise and how they should be handled. This helps other developers understand the expected behavior and handle exceptions appropriately.\n",
    "\n",
    "Use context managers (with statement): Utilize context managers (with statement) for managing resources that need to be cleaned up, such as file operations or database connections. They automatically handle resource cleanup, even in the presence of exceptions.\n",
    "\n",
    "By following these best practices, you can write more robust and maintainable Python code with effective exception handling.\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
